modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "WTFPL License"

[[mods]]
modId = "ommscontrollerarchitectury"
version = "${version}"
displayName = "Example Mod"
authors = "ZhuRuoLing"
description = '''
ree!
'''
#logoFile = ""

[[dependencies.ommscontrollerarchitectury]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.ommscontrollerarchitectury]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.ommscontrollerarchitectury]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "SERVER"